config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrattions" }
  
   get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hit The Lip</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  

    <meta name="viewport" content="width=device-width, initial-scale=1">
     <%= csrf_meta_tags %>

  </head>

  <body>
  <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p id="alert" class="alert alert-alert"><%= alert %></p>
  <% end %>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid ">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
         <div class="projectName navbar-brand">
          <%= image_tag('hittheliplogo.png') %>
        </div> <!-- end projectName-->
      </div><!-- end navbar-header-->

      <div class="form_box">
        <%= form_tag("/products", method: "get", class: "form") do %>
          <%= label_tag(:q, " ") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Search") %>
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right" id="navbar-right">
        <nav class="nav nav-inline">
          <ul class="list-inline">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", static_pages_about_path %></li>
            <li><%= link_to "Store",  products_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
          </ul>
            <ul class="nav navbar-right">
              <li>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              <% else %>
                <%=link_to('Login', new_user_session_path) %>
              <% end %>
              </li>
          </ul>
         </nav><!-- end of nav-->
      </div><!--end collapse navbar-->
     </div><!-- end container fluid -->
   </nav>
  
    <%= yield %>

 <footer class="footer">
  <p>&copy 2017 Hit The Lip</p>
 </footer>
  </body>

</html>